In [1]:
print("this is tutorial on tensorflow")

this is tutorial on tensorflow


In [2]:

import numpy
import tensorflow as tf


In [3]:
# creating different type of tensors(vectors)
string=tf.Variable("this is a string tensor",tf.string)
num=tf.Variable(4,tf.int16)
floatnum=tf.Variable(3.42,tf.float16)

rank of a tensor is defined as the number of dimensions it has

In [4]:
rank1=tf.Variable(["hellow","worls"],tf.string)
rank2=tf.Variable([["hellow","world"],["its","good day"]],tf.string)

In [5]:
#checking the rank of above tensor
tf.rank(rank2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

shape of tensor tells us the shape of the tensor similar to the shape of any standard matrix

In [6]:
rank1.shape

TensorShape([2])

shape manupalation in tensor

In [7]:
tensor1=tf.ones([1,2,3])
tensor2=tf.reshape(tensor1,[2,3,1])
tensor3=tf.reshape(tensor2,[3,-1])

In [8]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


type of tensors: 
variable, constant, placeholder, sparseTensor

In [9]:
t=tf.zeros([5,5,5,5])
print(t)
#to flattern the above tensor: 
t=tf.reshape(t,[625])
print(t)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0.